name: device_security_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.3

  # Location & GPS
  geolocator: ^13.0.2
  permission_handler: ^11.3.1

  # Camera & Intruder
  camera: ^0.11.1
  image_picker: ^1.1.2

  # SIM & Device Info
  telephony: ^0.2.0
  device_info_plus: ^11.3.3

  # Background Services
  workmanager: ^0.5.2
  flutter_background_service: ^5.1.0

  # Contacts Backup
  flutter_contacts: ^1.1.8

  # Utilities
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  intl: ^0.19.0

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true