// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBdtzYTo1mZdcK5EwKispYWlO-fFDqhb8',
    appId: '1:313264855777:web:b0c8a0a28ca7ac3cdfb5a0',
    messagingSenderId: '313264855777',
    projectId: 'device-protection-app',
    authDomain: 'device-protection-app.firebaseapp.com',
    storageBucket: 'device-protection-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlUC0-960SEP20WzIhb2HAt7WDQnGI1N0',
    appId: '1:313264855777:android:e2f6250cac0cad4bdfb5a0',
    messagingSenderId: '313264855777',
    projectId: 'device-protection-app',
    storageBucket: 'device-protection-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Ih6uGkh57WJtbpsMHNXDegrzL02nE-E',
    appId: '1:313264855777:ios:022506c5783db957dfb5a0',
    messagingSenderId: '313264855777',
    projectId: 'device-protection-app',
    storageBucket: 'device-protection-app.firebasestorage.app',
    iosClientId: '313264855777-i3kva7hd5dk8fkmp518mtdrukus41nol.apps.googleusercontent.com',
    iosBundleId: 'com.example.deviceSecuritySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Ih6uGkh57WJtbpsMHNXDegrzL02nE-E',
    appId: '1:313264855777:ios:022506c5783db957dfb5a0',
    messagingSenderId: '313264855777',
    projectId: 'device-protection-app',
    storageBucket: 'device-protection-app.firebasestorage.app',
    iosClientId: '313264855777-i3kva7hd5dk8fkmp518mtdrukus41nol.apps.googleusercontent.com',
    iosBundleId: 'com.example.deviceSecuritySystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBdtzYTo1mZdcK5EwKispYWlO-fFDqhb8',
    appId: '1:313264855777:web:1aec3f8f3db6ba74dfb5a0',
    messagingSenderId: '313264855777',
    projectId: 'device-protection-app',
    authDomain: 'device-protection-app.firebaseapp.com',
    storageBucket: 'device-protection-app.firebasestorage.app',
  );

}